/****************************************************************************
* (C) 1999-2005 by BECK IPC GmbH
*
*  BECK IPC GmbH
*  Germany
*  
*  http://www.beck-ipc.com
*
* ---------------------------------------------------------------------------
*  Module        : CLIB.H
*  Function      : RTOS C library include file
* ---------------------------------------------------------------------------

   $Header: /home/xubuntu/berlios_backup/github/tmp-cvs/esemerklin/Repository/Socket_Server/CLIB.H,v 1.1 2006/06/05 12:36:47 nadorwo Exp $

*****************************************************************************/


#ifndef _CLIB_H_
  #define _CLIB_H_

  #include "BIOS_API.H"
  #include "CAN_API.H"
  #include "CGIAPI.H"
  #include "DNSAPI.H"
  #include "EXTDISK.H"
  #include "FOSSIL.H"
  #include "HELPER.H"
  #include "HWAPI.H"
  #include "I2C_API.H"
  #include "SPIAPI.H"
  #include "PKTDRV.H"
  #include "RTOS.H"
  #include "RTXERR.H"
  #include "TCPIP.H"
  #include "usb_api.h"
  #include "usb_spec.h"

#endif // _CLIB_H_
